# Generated by Django 5.2.4 on 2026-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('https_enabled', models.BooleanField(default=False, help_text='Redirige HTTP→HTTPS, active les cookies sécurisés et HSTS. La terminaison TLS est assurée par le reverse proxy (nginx).', verbose_name='HTTPS activé')),
                ('https_domain', models.CharField(blank=True, default='', help_text='Domaine public servi en HTTPS (ex. agent.cyonima.dev).', max_length=255, verbose_name='Domaine HTTPS')),
                ('tls_cert_pem', models.TextField(blank=True, default='', verbose_name='Certificat TLS (PEM)')),
                ('tls_key_pem', models.TextField(blank=True, default='', verbose_name='Clé privée TLS (PEM)')),
                ('ldap_enabled', models.BooleanField(default=False, verbose_name='LDAP activé')),
                ('ldap_type', models.CharField(choices=[('ad', 'Active Directory'), ('openldap', 'OpenLDAP')], default='ad', max_length=16, verbose_name="Type d'annuaire")),
                ('ldap_server_uri', models.CharField(blank=True, default='', help_text='Ex. ldap://dc.ad.example.com:389 ou ldaps://… (LDAPS avec TLS).', max_length=255, verbose_name='URI du serveur')),
                ('ldap_bind_dn', models.CharField(blank=True, default='', max_length=255, verbose_name='DN de liaison (service account)')),
                ('ldap_bind_password', models.CharField(blank=True, default='', max_length=255, verbose_name='Mot de passe de liaison')),
                ('ldap_base_dn', models.CharField(blank=True, default='', help_text='Base de recherche des utilisateurs (ex. dc=ad,dc=example,dc=com).', max_length=255, verbose_name='DN de base')),
                ('ldap_login_attribute', models.CharField(default='sAMAccountName', help_text="Attribut contenant l'identifiant saisi en bas de page : sAMAccountName (AD), uid (OpenLDAP) ou mail.", max_length=64, verbose_name='Attribut de connexion')),
                ('ldap_user_filter', models.CharField(blank=True, default='', help_text="Filtre de recherche LDAP, %(user)s est remplacé par l'identifiant. Laissé vide : cet attribut est dérivé de « Attribut de connexion ».", max_length=255, verbose_name='Filtre utilisateur')),
                ('ldap_email_domain', models.CharField(blank=True, default='', help_text="Si l'annuaire ne fournit pas d'email (ex. samaccountname), les comptes reçoivent <identifiant>@<ce domaine>.", max_length=255, verbose_name='Domaine email de repli')),
                ('ldap_start_tls', models.BooleanField(default=True, help_text='Active StartTLS sur la liaison (ldap://). Recommandé.', verbose_name='StartTLS')),
                ('ldap_user_attr', models.CharField(default='displayName', help_text='Attribut LDAP du nom complet (displayName ou cn).', max_length=64, verbose_name='Attribut nom complet')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configuration système',
            },
        ),
    ]
