# Generated by Django 5.2.4 on 2026-09-21 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_id', models.CharField(db_index=True, max_length=64)),
                ('tool', models.CharField(max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('preview', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('denied', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='agent_sessions.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
