# Generated by Django 5.2.4 on 2026-09-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrequest',
            options={'ordering': ['created_at'], 'verbose_name': "Demande d'approbation", 'verbose_name_plural': "Demandes d'approbation"},
        ),
    ]
