# Generated by Django 5.2.4 on 2026-09-21 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama')], default='ollama', max_length=16)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('reasoning', models.CharField(default='auto', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'Système'), ('user', 'Utilisateur'), ('assistant', 'Assistant'), ('tool', 'Outil')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_call_id', models.CharField(blank=True, max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_sessions.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
