# Generated by Django 5.2.4 on 2026-09-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
