# Generated by Django 5.2.4 on 2026-09-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0002_message_run_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
