"""Catalogue de modèles Ollama proposés par défaut.

Reproduit la sélection du client lourd (`docs/models-catalog.toml` dans
Cyonima-code-agent) pour offrir les mêmes modèles installables depuis la
page « Modèles Ollama » du web. Tous les modèles sont pullés via Ollama.
"""

CATALOG_MODELS: list[dict] = [
    # Entry-level (1.5B-3B) — 2-4 Go RAM
    {
        "id": "qwen2.5-3b-instruct-q4_k_m",
        "name": "Qwen 2.5 3B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "qwen2.5:3b",
    },
    {
        "id": "deepseek-r1-distill-qwen-1.5b-q4_k_m",
        "name": "DeepSeek R1 Distill Qwen 1.5B (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "MIT (DeepSeek distill)",
        "ram_min_gb": 2,
        "model_type": "general",
        "ollama_tag": "deepseek-r1:1.5b",
    },
    {
        "id": "llama-3.2-3b-instruct-q4_k_m",
        "name": "Llama 3.2 3B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Llama Community License",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "llama3.2:3b",
    },
    # Gemma 4 — famille QAT (Apache-2.0)
    {
        "id": "gemma-4-12b-it-qat-q4_0",
        "name": "Gemma 4 12B IT QAT (Q4_0) — reasoning+code, vision",
        "quantization": "Q4_0",
        "license": "Apache-2.0 (Gemma 4)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "gemma4:12b",
    },
    {
        "id": "gemma-4-31b-it-qat-q4_0",
        "name": "Gemma 4 31B IT QAT (Q4_0) — dense, frontier reasoning+code",
        "quantization": "Q4_0",
        "license": "Apache-2.0 (Gemma 4)",
        "ram_min_gb": 21,
        "model_type": "general",
        "ollama_tag": "gemma4:31b",
    },
    # Code spécialisé — 7B à 32B
    {
        "id": "qwen2.5-coder-7b-instruct-q4_k_m",
        "name": "Qwen 2.5 Coder 7B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 8,
        "model_type": "coding",
        "ollama_tag": "qwen2.5-coder:7b",
    },
    {
        "id": "qwen2.5-coder-14b-instruct-q4_k_m",
        "name": "Qwen 2.5 Coder 14B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 12,
        "model_type": "coding",
        "ollama_tag": "qwen2.5-coder:14b",
    },
    {
        "id": "qwen2.5-coder-32b-instruct-q4_k_m",
        "name": "Qwen 2.5 Coder 32B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "coding",
        "ollama_tag": "qwen2.5-coder:32b",
    },
    # Reasoning (DeepSeek R1 distillations) — 8B à 32B
    {
        "id": "deepseek-r1-distill-llama-8b-q4_k_m",
        "name": "DeepSeek R1 Distill Llama 8B (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "MIT (DeepSeek distill)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "deepseek-r1:8b",
    },
    {
        "id": "deepseek-r1-distill-qwen-32b-q4_k_m",
        "name": "DeepSeek R1 Distill Qwen 32B (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "MIT (DeepSeek distill)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "deepseek-r1:32b",
    },
    # Généralistes — 7B à 32B
    {
        "id": "llama-3.1-8b-instruct-q4_k_m",
        "name": "Llama 3.1 8B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Llama Community License",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "llama3.1:8b",
    },
    {
        "id": "mistral-7b-instruct-v0.3-q4_k_m",
        "name": "Mistral 7B Instruct v0.3 (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Mistral)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "mistral:7b",
    },
    {
        "id": "phi-4-14b-instruct-q4_k_m",
        "name": "Phi-4 14B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "MIT (Microsoft Phi-4)",
        "ram_min_gb": 12,
        "model_type": "general",
        "ollama_tag": "phi4:14b",
    },
    {
        "id": "qwen2.5-14b-instruct-q4_k_m",
        "name": "Qwen 2.5 14B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 12,
        "model_type": "general",
        "ollama_tag": "qwen2.5:14b",
    },
    {
        "id": "qwen2.5-32b-instruct-q4_k_m",
        "name": "Qwen 2.5 32B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "qwen2.5:32b",
    },
    # Multimodal (vision + texte)
    {
        "id": "qwen2.5-vl-7b-instruct-q4_k_m",
        "name": "Qwen 2.5 VL 7B Instruct (Q4_K_M)",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "qwen2.5vl:7b",
    },
    # High-end — 70B
    {
        "id": "llama-3.1-70b-instruct-q2_k",
        "name": "Llama 3.1 70B Instruct (Q2_K) — très lent, 70B quantizé bas",
        "quantization": "Q2_K",
        "license": "Llama Community License",
        "ram_min_gb": 32,
        "model_type": "general",
        "ollama_tag": "llama3.1:70b",
    },
    # Coding agentique nouvelle génération
    {
        "id": "devstral-small-24b-q4_k_m",
        "name": "Devstral Small 24B (Q4_K_M) — agent de code multi-fichiers",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Mistral)",
        "ram_min_gb": 18,
        "model_type": "coding",
        "ollama_tag": "devstral:24b",
    },
    {
        "id": "qwen3-coder-30b-a3b-q4_k_m",
        "name": "Qwen3 Coder 30B-A3B (Q4_K_M) — MoE coding agentique",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "coding",
        "ollama_tag": "qwen3-coder:30b",
    },
    # Généralistes nouvelle génération (Qwen3)
    {
        "id": "qwen3-4b-q4_k_m",
        "name": "Qwen 3 4B (Q4_K_M) — léger, tools + thinking",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "qwen3:4b",
    },
    {
        "id": "qwen3-8b-q4_k_m",
        "name": "Qwen 3 8B (Q4_K_M) — tools + thinking",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "qwen3:8b",
    },
    {
        "id": "qwen3-14b-q4_k_m",
        "name": "Qwen 3 14B (Q4_K_M) — tools + thinking",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 12,
        "model_type": "general",
        "ollama_tag": "qwen3:14b",
    },
    {
        "id": "qwen3-30b-a3b-q4_k_m",
        "name": "Qwen 3 30B-A3B (Q4_K_M) — MoE rapide",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "qwen3:30b",
    },
    {
        "id": "qwen3-32b-q4_k_m",
        "name": "Qwen 3 32B (Q4_K_M) — dense haut de gamme",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "qwen3:32b",
    },
    # gpt-oss (OpenAI, poids ouverts)
    {
        "id": "gpt-oss-20b-q4_k_m",
        "name": "gpt-oss 20B (MoE) — raisonnement + agentique",
        "quantization": "MXFP4",
        "license": "Apache-2.0 (OpenAI gpt-oss)",
        "ram_min_gb": 16,
        "model_type": "general",
        "ollama_tag": "gpt-oss:20b",
    },
    # Llama 3.3
    {
        "id": "llama-3.3-70b-instruct-q4_k_m",
        "name": "Llama 3.3 70B Instruct (Q4_K_M) — proche de 3.1 405B",
        "quantization": "Q4_K_M",
        "license": "Llama Community License",
        "ram_min_gb": 40,
        "model_type": "general",
        "ollama_tag": "llama3.3:70b",
    },
    # Gemma 3 (vision, single-GPU)
    {
        "id": "gemma-3-4b-it-q4_k_m",
        "name": "Gemma 3 4B IT (Q4_K_M) — vision, léger",
        "quantization": "Q4_K_M",
        "license": "Gemma Terms (Google)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "gemma3:4b",
    },
    {
        "id": "gemma-3-12b-it-q4_k_m",
        "name": "Gemma 3 12B IT (Q4_K_M) — vision, équilibré",
        "quantization": "Q4_K_M",
        "license": "Gemma Terms (Google)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "gemma3:12b",
    },
    {
        "id": "gemma-3-27b-it-q4_k_m",
        "name": "Gemma 3 27B IT (Q4_K_M) — vision, single-GPU",
        "quantization": "Q4_K_M",
        "license": "Gemma Terms (Google)",
        "ram_min_gb": 20,
        "model_type": "general",
        "ollama_tag": "gemma3:27b",
    },
    # Raisonnement
    {
        "id": "qwq-32b-q4_k_m",
        "name": "QwQ 32B (Q4_K_M) — raisonnement Qwen",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "qwq:32b",
    },
    {
        "id": "phi-4-reasoning-14b-q4_k_m",
        "name": "Phi-4 Reasoning 14B (Q4_K_M) — raisonnement compact",
        "quantization": "Q4_K_M",
        "license": "MIT (Microsoft)",
        "ram_min_gb": 12,
        "model_type": "general",
        "ollama_tag": "phi4-reasoning:14b",
    },
    {
        "id": "magistral-24b-q4_k_m",
        "name": "Magistral 24B (Q4_K_M) — raisonnement Mistral",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Mistral)",
        "ram_min_gb": 18,
        "model_type": "general",
        "ollama_tag": "magistral:24b",
    },
    # Vision nouvelle génération (Qwen3-VL)
    {
        "id": "qwen3-vl-4b-q4_k_m",
        "name": "Qwen 3 VL 4B (Q4_K_M) — vision, léger",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "qwen3-vl:4b",
    },
    {
        "id": "qwen3-vl-8b-q4_k_m",
        "name": "Qwen 3 VL 8B (Q4_K_M) — vision",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "qwen3-vl:8b",
    },
    {
        "id": "qwen3-vl-30b-a3b-q4_k_m",
        "name": "Qwen 3 VL 30B-A3B (Q4_K_M) — vision, MoE",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "qwen3-vl:30b",
    },
    # Léger / edge & entreprise
    {
        "id": "phi-4-mini-3.8b-q4_k_m",
        "name": "Phi-4 Mini 3.8B (Q4_K_M) — function calling, multilingue",
        "quantization": "Q4_K_M",
        "license": "MIT (Microsoft)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "phi4-mini:3.8b",
    },
    {
        "id": "granite-4.1-3b-q4_k_m",
        "name": "Granite 4.1 3B (Q4_K_M) — tools + RAG, Apache-2.0",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (IBM Granite)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "granite4.1:3b",
    },
    {
        "id": "granite-4.1-8b-q4_k_m",
        "name": "Granite 4.1 8B (Q4_K_M) — tools + RAG, Apache-2.0",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (IBM Granite)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "granite4.1:8b",
    },
    {
        "id": "mistral-small-3.2-24b-q4_k_m",
        "name": "Mistral Small 3.2 24B (Q4_K_M) — vision + tools",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Mistral)",
        "ram_min_gb": 18,
        "model_type": "general",
        "ollama_tag": "mistral-small3.2:24b",
    },
    # Qwen 3.6 / 3.8 (agentic coding, Apache-2.0)
    {
        "id": "qwen3.8-27b-q4_k_m",
        "name": "Qwen 3.8 27B (Q4_K_M) — agentic coding, vision + thinking",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "coding",
        "ollama_tag": "qwen3.8:27b",
    },
    {
        "id": "qwen3.6-27b-q4_k_m",
        "name": "Qwen 3.6 27B (Q4_K_M) — agentic coding + thinking",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 24,
        "model_type": "coding",
        "ollama_tag": "qwen3.6:27b",
    },
    {
        "id": "qwen3.6-35b-a3b-q4_k_m",
        "name": "Qwen 3.6 35B-A3B (Q4_K_M) — MoE, agentic coding",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Qwen)",
        "ram_min_gb": 32,
        "model_type": "coding",
        "ollama_tag": "qwen3.6:35b",
    },
    # Muse Glimmer (Meta, Apache-2.0)
    {
        "id": "muse-glimmer-30b-q4_k_m",
        "name": "Muse Glimmer 30B (Q4_K_M) — agent local Meta, vision + tools",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (Meta)",
        "ram_min_gb": 24,
        "model_type": "coding",
        "ollama_tag": "muse-glimmer:30b",
    },
    # NVIDIA Nemotron (open, agents / multimodal)
    {
        "id": "nemotron-3.5-lightning-30b-q4_k_m",
        "name": "Nemotron 3.5 Lightning 30B (Q4_K_M) — MoE 3B actifs, agents",
        "quantization": "Q4_K_M",
        "license": "NVIDIA Open Model License",
        "ram_min_gb": 32,
        "model_type": "general",
        "ollama_tag": "nemotron-3.5-lightning:30b",
    },
    {
        "id": "nemotron3-33b-q4_k_m",
        "name": "Nemotron 3 Nano Omni 33B (Q4_K_M) — multimodal (video/audio/image)",
        "quantization": "Q4_K_M",
        "license": "NVIDIA Open Model License",
        "ram_min_gb": 32,
        "model_type": "general",
        "ollama_tag": "nemotron3:33b",
    },
    # IBM Granite 4.2 (Apache-2.0, tools + thinking)
    {
        "id": "granite-4.2-3b-q4_k_m",
        "name": "Granite 4.2 3B (Q4_K_M) — tools + thinking + RAG",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (IBM Granite)",
        "ram_min_gb": 4,
        "model_type": "general",
        "ollama_tag": "granite4.2:3b",
    },
    {
        "id": "granite-4.2-8b-q4_k_m",
        "name": "Granite 4.2 8B (Q4_K_M) — tools + thinking + RAG",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (IBM Granite)",
        "ram_min_gb": 8,
        "model_type": "general",
        "ollama_tag": "granite4.2:8b",
    },
    {
        "id": "granite-4.2-30b-q4_k_m",
        "name": "Granite 4.2 30B (Q4_K_M) — tools + thinking + RAG",
        "quantization": "Q4_K_M",
        "license": "Apache-2.0 (IBM Granite)",
        "ram_min_gb": 24,
        "model_type": "general",
        "ollama_tag": "granite4.2:30b",
    },
    # Ornith (MIT, coding agentique auto-améliorant)
    {
        "id": "ornith-9b-q4_k_m",
        "name": "Ornith 9B (Q4_K_M) — coding agentique, MIT",
        "quantization": "Q4_K_M",
        "license": "MIT (Ornith)",
        "ram_min_gb": 8,
        "model_type": "coding",
        "ollama_tag": "ornith:9b",
    },
    {
        "id": "ornith-35b-q4_k_m",
        "name": "Ornith 35B (Q4_K_M) — coding agentique, MIT",
        "quantization": "Q4_K_M",
        "license": "MIT (Ornith)",
        "ram_min_gb": 28,
        "model_type": "coding",
        "ollama_tag": "ornith:35b",
    },
    {
        "id": "ornith-1.5-9b-q4_k_m",
        "name": "Ornith 1.5 9B (Q4_K_M) — vision + coding",
        "quantization": "Q4_K_M",
        "license": "MIT (Ornith)",
        "ram_min_gb": 8,
        "model_type": "coding",
        "ollama_tag": "ornith-1.5:9b",
    },
    {
        "id": "ornith-1.5-35b-a3b-q4_k_m",
        "name": "Ornith 1.5 35B-A3B (Q4_K_M) — vision + coding",
        "quantization": "Q4_K_M",
        "license": "MIT (Ornith)",
        "ram_min_gb": 32,
        "model_type": "coding",
        "ollama_tag": "ornith-1.5:35b",
    },
]


def catalog_models() -> list[dict]:
    """Retourne une copie des entrées du catalogue."""
    return [dict(m) for m in CATALOG_MODELS]