# Generated by Django 5.2.4 on 2026-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='allow_network',
            field=models.BooleanField(default=False, help_text="Autorise l'accès réseau dans le sandbox (désactivé par défaut)."),
        ),
    ]
