# Generated by Django 5.2.4 on 2026-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_allow_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
        migrations.AddField(
            model_name='workspace',
            name='local_path',
            field=models.CharField(blank=True, help_text="Chemin local (sur le serveur) d'un dossier existant à utiliser comme workspace.", max_length=1024),
        ),
    ]
