from .base import *  # noqa: F401,F403

DEBUG = False

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Sécurité production
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = "DENY"

ACCOUNT_EMAIL_VERIFICATION = "mandatory"
