# Generated by Django 5.2.4 on 2026-09-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organisation', 'verbose_name_plural': 'Organisations'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Équipe', 'verbose_name_plural': 'Équipes'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'verbose_name': "Membre d'équipe", 'verbose_name_plural': "Membres d'équipe"},
        ),
    ]
